map_test: Replace PAGE_SIZE with local variable name
PAGE_SIZE is already a define in libc implementations global namespace
e.g. in musl. Therefore its best to use a unique variable name to not
stamp on the global definition.

Fixes
src/map_test.cpp:59:23: error: expected unqualified-id
unsigned long PAGE_SIZE = sysconf(_SC_PAGESIZE);
^
/usr/include/limits.h:89:19: note: expanded from macro 'PAGE_SIZE'
^
/usr/include/bits/limits.h:3:18: note: expanded from macro 'PAGESIZE'
^

Signed-off-by: Khem Raj <raj.khem@gmail.com>